// import type { CylinderProps } from '@react-three/cannon'
// import { useCompoundBody } from '@react-three/cannon'
// import { useGLTF } from '@react-three/drei'
// import { forwardRef } from 'react'
// import type { Group, Material, Mesh } from 'three'
// import type { GLTF } from 'three-stdlib/loaders/GLTFLoader'

// useGLTF.preload('/wheel.glb')

// // Initially Auto-generated by: https://github.com/pmndrs/gltfjsx

// type WheelGLTF = GLTF & {
//   materials: Record<'Chrom' | 'Rubber' | 'Steel', Material>
//   nodes: Record<'wheel_1' | 'wheel_2' | 'wheel_3', Mesh>
// }

// type WheelProps = CylinderProps & {
//   leftSide?: boolean
//   radius: number
// }

// export const Wheel = forwardRef<Group, WheelProps>(({ leftSide, radius = 0.7, ...props }, ref) => {
//   const {
//     materials: { Chrom, Rubber, Steel },
//     nodes,
//   } = useGLTF('/wheel.glb') as WheelGLTF

//   useCompoundBody(
//     () => ({
//       collisionFilterGroup: 0,
//       mass: 1,
//       material: 'wheel',
//       shapes: [{ args: [radius, radius, 0.5, 16], rotation: [0, 0, -Math.PI / 2], type: 'Cylinder' }],
//       type: 'Kinematic',
//       ...props,
//     }),
//     ref,
//   )

//   return (
//     <group ref={ref}>
//       <group rotation={[0, 0, ((leftSide ? 1 : -1) * Math.PI) / 2]}>
//         <mesh material={Rubber} geometry={nodes.wheel_1.geometry} />
//         <mesh material={Steel} geometry={nodes.wheel_2.geometry} />
//         <mesh material={Chrom} geometry={nodes.wheel_3.geometry} />
//       </group>
//     </group>
//   )
// })
import { forwardRef } from 'react'
import { useMemo } from 'react'
import THREE, { CylinderGeometry, Mesh, MeshStandardMaterial } from 'three'

type WheelProps = {
  leftSide?: boolean
  radius?: number
}

const Wheel = useMemo(() => {
  return [0, 1, 2, 3].map(() => {
    const geometry = new THREE.CylinderGeometry(0.7, 0.7, 0.7 / 2, 20);
    const material = new THREE.MeshStandardMaterial({ color: 'black' });
    const mesh = new THREE.Mesh(geometry, material);
    // mesh.rotation.z = Math.PI / 2; // rotate so wheel lays flat
    return mesh;
  });
}, []);

// const Wheel = forwardRef<Mesh, WheelProps>(({ leftSide = false, radius = 0.12 }, ref) => {
//   return (
//     <mesh ref={ref} rotation={[Math.PI / 2, 0, 0]}>
//       <cylinderGeometry args={[radius, radius, 0.3, 32]} />
//       <meshStandardMaterial color={leftSide ? 'black' : 'gray'} />
//     </mesh>
//   )
// })

export { Wheel }