name: Initial install

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: self-hosted
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4
      - name: Set up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
      - name: Cache node modules
        id: cache-backend
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{runner.os}}-backend-${{ env.cache-name }}-${{ hashFiles('package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-backend-${{ env.cache-name }}-
            ${{ runner.os }}-backend-
            ${{ runner.os }}-   
      - name: Install Dependencies
        run: |
          cd backend
          npm i
      - name: Check linting and formatting
        run: |
          cd backend
          npm run lint
      - name: Execute test cases
        run: echo testing...
  frontend:
    needs: backend
    runs-on: self-hosted
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4
      - name: Set up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
      - name: Cache node modules
        id: cache-frontend
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{runner.os}}-frontend-${{env.cache-name}}-${{ hashFiles('frontend/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-frontend-${{ env.cache-name }}
            ${{ runner.os }}-frontend-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          cd frontend
          npm i
      - name: Check linting and formatting
        run: |
          cd frontend
          npm run lint
  build:
    needs: frontend
    runs-on: self-hosted
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4
      - name: Set up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
      - name: Use cache node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            frontend/node_modules
          key: |
            backend-cache-backend-${{ hashFiles('package-lock.json')}}
            frontend-cache-frontend-${{ hashFiles('frontend/package-lock.json')}}
      - name: Install Dependencies
        run: |
          cd backend
          npm i
          cd ../frontend
          npm i
      - name: Create production build
        run: |
          cd frontend
          npm run build